Repository ssm0318/WhoamI-Today-backend, pull requests merged in 2025-04, with the labels that each got.

#687 (#686) fix hyperlinkedidentityfield
  adoorback/check_in/serializers.py
  adoorback/like/serializers.py
  adoorback/note/serializers.py
  adoorback/qna/serializers.py
Labels: bug

#692 (#691) fix notification recent_actors error
  adoorback/notification/serializers.py
Labels: bug

#696 (#695) record username history
  adoorback/account/migrations/0030_user_username_history.py
  adoorback/account/models.py
  adoorback/account/views.py
  adoorback/adoorback/management/commands/update_username_history.py
Labels: feature

#697 (#686) prevent duplicate likes
  adoorback/like/views.py
Labels: bug

#698 (#694) add random recommended friends to 10
  adoorback/account/views.py
Labels: feature

#700 (#683) add more info to logs
  adoorback/adoorback/filters.py
  adoorback/adoorback/safe_formatter.py
  adoorback/adoorback/settings/base.py
  adoorback/adoorback/utils/alerts.py
  adoorback/adoorback/utils/validators.py
  adoorback/requirements.txt
Labels: feature

#703 (#702) handle likecreate error
  adoorback/like/views.py
Labels: bug

#704 (#688) silence slack alerts
  adoorback/account/serializers.py
  adoorback/adoorback/utils/exceptions.py
  adoorback/adoorback/utils/validators.py
Labels: refactoring

#706 [#699] Add user_list filtering for UserRecommendedFriendsList
  adoorback/account/views.py
Labels: bug, 🚧 under construction 🚧

#710 (#709) update user change versions command
  adoorback/adoorback/management/commands/update_versions_korean.py
  adoorback/adoorback/management/commands/update_versions_us.py
Labels: refactoring

#712 (#711) fix noti count for users after version change
  adoorback/account/serializers.py
Labels: bug

#708 (#707) add signup inviter email & date of birth validation
  adoorback/account/serializers.py
  adoorback/account/urls.py
  adoorback/account/views.py
  adoorback/adoorback/locale/en/LC_MESSAGES/django.mo
  adoorback/adoorback/locale/en/LC_MESSAGES/django.po
  adoorback/adoorback/locale/ko/LC_MESSAGES/django.mo
  adoorback/adoorback/locale/ko/LC_MESSAGES/django.po
  adoorback/adoorback/utils/exceptions.py
Labels: feature

#717 (#716) add error code for duplicate like
  adoorback/adoorback/locale/en/LC_MESSAGES/django.mo
  adoorback/adoorback/locale/en/LC_MESSAGES/django.po
  adoorback/adoorback/locale/ko/LC_MESSAGES/django.mo
  adoorback/adoorback/locale/ko/LC_MESSAGES/django.po
  adoorback/like/views.py
Labels: feature

#721 (#718) set has_changed_pw = True for signup users
  adoorback/account/serializers.py
Labels: bug

#722 (#720) add email verification
  adoorback/account/email.py
  adoorback/account/migrations/0031_user_email_verified.py
  adoorback/account/models.py
  adoorback/account/serializers.py
  adoorback/account/urls.py
  adoorback/account/views.py
  adoorback/adoorback/locale/en/LC_MESSAGES/django.mo
  adoorback/adoorback/locale/en/LC_MESSAGES/django.po
  adoorback/adoorback/locale/ko/LC_MESSAGES/django.mo
  adoorback/adoorback/locale/ko/LC_MESSAGES/django.po
Labels: feature

#723 (#720) set 365 days as limit for email verification token
  adoorback/account/email.py
  adoorback/account/views.py
Labels: feature

#724 (#719) add inviter to recommended friends
  adoorback/account/views.py
Labels: feature

#725 (#715) remove daily survey notification
  cron/crontab_jobs
Labels: feature

#727 (#726) add response audience check logic before sending noti
  adoorback/qna/models.py
Labels: bug
