Repository ssm0318/WhoamI-Today-backend, pull requests merged in 2025-02, with the labels that each got.

#445 (#433, #436) version change related implementation
  .gitignore
  adoorback/account/migrations/0015_user_current_ver_user_invited_from_user_user_group_and_more.py
  adoorback/account/models.py
  adoorback/account/serializers.py
  adoorback/account/urls.py
  adoorback/account/views.py
  adoorback/adoorback/utils/exceptions.py
  adoorback/adoorback/utils/helpers.py
Labels: feature, 🚧 under construction 🚧

#456 (#438) renew notification list when version changed
  adoorback/notification/views.py
Labels: feature

#457 [Reverted] (#450) Friend vs close friend implementation for ver.D and ver.E Common Features
  adoorback/note/migrations/0008_note_visibility.py
  adoorback/note/models.py
  adoorback/note/serializers.py
  adoorback/note/views.py
  adoorback/qna/migrations/0008_response_visibility.py
  adoorback/qna/models.py
  adoorback/qna/serializers.py
  adoorback/qna/views.py
  adoorback/test/seed.py
Labels: feature, 🚧 under construction 🚧

#458 (#452) Ver.E Visibility Adjustment When Upgrading a Friend → Close Friend
  adoorback/account/migrations/0016_connection_user1_update_past_posts_and_more.py
  adoorback/account/models.py
  adoorback/account/serializers.py
  adoorback/account/views.py
  adoorback/note/models.py
  adoorback/qna/migrations/0009_alter_response_visibility.py
  adoorback/qna/models.py
Labels: feature, 🚧 under construction 🚧

#464 (#463) resolve migration conflict
  adoorback/account/migrations/0017_merge_20250207_2123.py
Labels: bug

#465 (#461) remove unnecessary functions related to version
  .gitignore
  adoorback/account/serializers.py
  adoorback/account/urls.py
  adoorback/account/views.py
  adoorback/adoorback/utils/exceptions.py
  adoorback/adoorback/utils/helpers.py
Labels: refactoring

#466 (#454) implement current_ver batch update method
  .gitignore
  adoorback/account/management/commands/update_versions.py
Labels: feature

#462 [#437] Friend Request Validation for Different User Groups
  adoorback/account/serializers.py
  adoorback/account/views.py
Labels: feature, 🚧 under construction 🚧

#470 (#469) fix signup error
  adoorback/account/serializers.py
Labels: bug

#475 (#473) fix ping noti redirect_url
  adoorback/ping/models.py
Labels: bug

#477 (#460) implement session tracking related APIs
  adoorback/account/cron.py
  adoorback/account/migrations/0018_appsession.py
  adoorback/account/migrations/0019_appsession_last_ping_time.py
  adoorback/account/models.py
  adoorback/account/serializers.py
  adoorback/account/urls.py
  adoorback/account/views.py
  adoorback/adoorback/settings/base.py
  adoorback/adoorback/test/seed.py
  adoorback/qna/cron.py
Labels: feature, 🚧 under construction 🚧

#479 (#478) set max length as 10000 for ping
  adoorback/ping/models.py
Labels: refactoring

#472 [#397] Reset Password Security Enhancement
  adoorback/account/email.py
  adoorback/adoorback/settings/base.py
Labels: 🚧 under construction 🚧, refactoring

#489 [#487] Refactoring Comment/Reply Sorting Chronological Order
  adoorback/comment/serializers.py
  adoorback/note/views.py
  adoorback/qna/views.py
Labels: refactoring
