Repository ssm0318/WhoamI-Today-backend, pull requests merged in 2025-03, with the labels that each got.

#494 (#493) rename session ping to touch
  adoorback/account/cron.py
  adoorback/account/migrations/0020_rename_last_ping_time_appsession_last_touch_time.py
  adoorback/account/models.py
  adoorback/account/urls.py
  adoorback/account/views.py
  adoorback/ping/migrations/0002_alter_ping_content.py
Labels: refactoring

#498 (#482) fix superuser email in daily noti cron
  adoorback/account/cron.py
Labels: bug

#501 (#499) get rid of notifications after signup
  adoorback/account/cron.py
  adoorback/account/migrations/0021_remove_user_signup_noti_status.py
  adoorback/account/models.py
Labels: refactoring

#500 (#483) add branching for daily notification according to version
  adoorback/account/cron.py
Labels: feature

#497 (#495) Fix close friend upgrade related bugs
  adoorback/adoorback/test/seed.py
  adoorback/note/models.py
  adoorback/qna/models.py
Labels: bug

#507 (#506) modify get_object() return value of end & touch session APIs
  adoorback/account/views.py
Labels: bug

#508 (#504) change visitor tracking module session_key length limit
  adoorback/adoorback/apps.py
  adoorback/adoorback/settings/base.py
Labels: bug

#503 (#502) Error occurs in the local environment at user/friends/.
  adoorback/note/models.py
  adoorback/qna/models.py
Labels: bug

#511 (#502) fix is_close_friend parameter error
  adoorback/note/models.py
  adoorback/qna/models.py
Labels: bug

#516 (#513) add username field to ping list API
  adoorback/ping/views.py
Labels: feature

#519 (#515) recommend random 3 users when no recommended friends
  adoorback/account/views.py
Labels: feature

#471 [#383] Bug fix for notification update error when unliking
  adoorback/like/models.py
  adoorback/notification/helpers.py
  adoorback/notification/models.py
Labels: bug

#539 (#520) add load_questions command
  adoorback/account/management/commands/load_questions.py
Labels: feature

#540 (#535) change ping notification redirect url
  adoorback/ping/models.py
Labels: bug

#541 (#534) set notification message limit to 300
  adoorback/notification/migrations/0008_alter_notification_message_and_more.py
  adoorback/notification/models.py
Labels: bug

#543 (#530) fix redirect url for 'became friends' notification when username changed
  adoorback/account/views.py
Labels: bug

#544 (#527) exclude superuser and friend request received users from recommended friends
  adoorback/account/views.py
Labels: refactoring

#545 (#529) fix post_delete FriendRequest method to post_save
  adoorback/account/models.py
Labels: bug

#549 (#531) make requestee_choice optional in ver.Q friend request update api
  adoorback/account/serializers.py
Labels: bug

#554 (#553) filter feed post list using is_audience
  adoorback/account/views.py
Labels: bug

#555 (#552) raise error instead of returning PermissionDenied object
  adoorback/note/views.py
Labels: bug

#556 (#547) mark all notes in feed as read
  adoorback/account/views.py
Labels: feature

#532 [#496] Functionality for update_past_posts in ver.Q
  adoorback/account/migrations/0023_friendrequest_requestee_update_past_posts_and_more.py
  adoorback/account/models.py
  adoorback/account/serializers.py
  adoorback/account/views.py
Labels: feature, 🚧 under construction 🚧

#565 (#559) add like_count to default feed API
  adoorback/account/views.py
  adoorback/note/serializers.py
Labels: feature

#568 (#561) make note/response interactions API available to friends
  adoorback/note/models.py
  adoorback/note/views.py
  adoorback/qna/serializers.py
  adoorback/qna/views.py
Labels: bug

#569 (#557) add friend friend list api
  adoorback/account/serializers.py
  adoorback/account/urls.py
  adoorback/account/views.py
Labels: feature

#571 (#542) add deliberate like noti delete logic after changing policy to soft_delete
  adoorback/like/models.py
Labels: bug

#572 (#566) change check-in availability to social battery
  adoorback/adoorback/test/seed.py
  adoorback/check_in/migrations/0005_remove_checkin_availability_checkin_social_battery.py
  adoorback/check_in/models.py
  adoorback/check_in/serializers.py
Labels: feature

#574 (#566) add persona to user
  adoorback/account/migrations/0024_user_persona.py
  adoorback/account/models.py
  adoorback/account/serializers.py
  adoorback/account/views.py
Labels: feature

#575 (#573) add visibility field to default note api
  adoorback/note/serializers.py
  adoorback/note/views.py
Labels: bug

#576 (#528) don't send notification to turn on push noti if enabled
  adoorback/account/views.py
Labels: bug

#577 (#566) fix persona parsing error
  adoorback/account/migrations/0025_alter_user_persona.py
  adoorback/account/models.py
  adoorback/account/serializers.py
  adoorback/account/views.py
Labels: bug

#580 (#578) increase persona length limit
  adoorback/account/migrations/0026_alter_user_persona.py
  adoorback/account/models.py
Labels: bug

#579 (#197) new prompts!!
  adoorback/adoorback/assets/questions.tsv
  adoorback/adoorback/assets/questions_old.tsv
Labels: enhancement

#581 (#578) fix persona initialize error
  adoorback/account/migrations/0027_alter_user_persona.py
  adoorback/account/models.py
Labels: bug

#582 (#515) recommended users should be in same group
  adoorback/account/views.py
Labels: bug

#593 (#584) add has_changed_pw field & API
  adoorback/account/migrations/0028_user_has_changed_pw.py
  adoorback/account/models.py
  adoorback/account/serializers.py
  adoorback/account/views.py
Labels: feature

#594 (#592) add email search logic
  adoorback/account/serializers.py
  adoorback/account/views.py
Labels: feature

#598 (#597) fix ping redirect_url
  adoorback/ping/models.py
Labels: bug

#602 (#583) add user group filtering logic to mutual friends
  adoorback/account/models.py
  adoorback/account/views.py
Labels: bug

#603 (#585) remove filtering for private replies for post author
  adoorback/comment/serializers.py
Labels: bug

#604 (#601) add unread_noti_cnt to GET user/me/
  adoorback/account/serializers.py
Labels: feature

#605 (#600) include replies in # of comments
  adoorback/adoorback/serializers.py
Labels: bug

#589 [#480] Ping Notification Grouping; Updating Language to use Message vs Ping
  adoorback/notification/models.py
  adoorback/notification/serializers.py
  adoorback/ping/models.py
Labels: feature

#607 (#606) group questions by selected date
  adoorback/qna/serializers.py
  adoorback/qna/views.py
Labels: refactoring

#608 (#591) change db backup period to 1 hour
  cron/crontab_jobs
  cron/scripts/db_backup.sh
Labels: refactoring

#617 (#612) add filtering by current_ver to recommended users (just in case)
  adoorback/account/views.py
Labels: bug

#590 [#509] Visually Separating Error Logs
  .gitignore
  adoorback/adoorback/settings/base.py
  docker-compose.production.yml
Labels: feature

#621 (#485) send firebase notification when noti is updated
  adoorback/notification/models.py
Labels: bug

#626 (#625) fix daily_questions to consider user's timezone
  adoorback/account/cron.py
  adoorback/account/email.py
  adoorback/account/views.py
  adoorback/notification/models.py
  adoorback/notification/views.py
  adoorback/qna/algorithms/data_crawler.py
  adoorback/qna/models.py
  adoorback/qna/views.py
Labels: bug

#627 (#599) fix recieved prompts language error; group prompts
  adoorback/account/views.py
  adoorback/notification/serializers.py
Labels: bug

#628 (#484) add pagination
  adoorback/account/views.py
  adoorback/qna/serializers.py
Labels: bug

#629 (#484) add created_at, is_recent fields
  adoorback/account/views.py
Labels: bug

#630 (#484) add id to response request list
  adoorback/account/views.py
Labels: bug

#635 (#634) do not make alerts for not authenticated cases
  adoorback/adoorback/utils/validators.py
Labels: bug

#636 hotfix: add log time by minutes in cron log
  cron/crontab_jobs
Labels: feature

#637 (#622) add permissiondenied to slack exclude list
  adoorback/adoorback/utils/validators.py
Labels: refactoring

#639 (#546) implement management command for batch user creation
  .gitignore
  adoorback/adoorback/management/commands/load_questions.py
  adoorback/adoorback/management/commands/load_users_from_csv.py
  adoorback/adoorback/management/commands/update_versions_korean.py
  adoorback/adoorback/management/commands/update_versions_us.py
  docker-compose.production.yml
Labels: feature

#644 (#643) change social battery wording
  adoorback/adoorback/test/seed.py
  adoorback/check_in/migrations/0006_alter_checkin_social_battery.py
  adoorback/check_in/models.py
Labels: refactoring

#647 (#533) [Bug] friend page sometimes throws error
  adoorback/adoorback/urls.py
Labels: bug

#649 (#642) modify load_users_from_csv - add country; change password
  .gitignore
  adoorback/adoorback/management/commands/load_users_from_csv.py
  docker-compose.production.yml
Labels: refactoring

#656 (#653) remove email search logic
  adoorback/account/views.py
Labels: feature

#658 (#657) exclude blocked users & superusers in search result
  adoorback/account/views.py
Labels: bug

#638 (#632) add user & token info to log
  adoorback/adoorback/authentication.py
  adoorback/adoorback/filters.py
  adoorback/adoorback/safe_formatter.py
  adoorback/adoorback/settings/base.py
  adoorback/adoorback/utils/authentication.py
Labels: feature

#662 (#632) add user_id to logging
  adoorback/adoorback/filters.py
  adoorback/adoorback/settings/base.py
Labels: feature

#664 (#632) add user info to slack alert; show only part of token
  adoorback/adoorback/filters.py
  adoorback/adoorback/utils/alerts.py
Labels: feature

#667 (#650) sort received prompts by created_at
  adoorback/account/views.py
Labels: bug

#669 (#668) modify load_users_from_csv
  .gitignore
  adoorback/adoorback/management/commands/load_users_from_csv.py
  docker-compose.production.yml
Labels: refactoring

#670 (#668) fix docker-compose file mount typo
  docker-compose.production.yml
Labels: bug

#673 (#672) prevent login 406 error
  adoorback/account/views.py
Labels: bug

#674 (#671) silence alerts for session related errors
  adoorback/account/views.py
  adoorback/adoorback/test/seed.py
Labels: refactoring

#675 (#672) remove authentication requirement from login
  adoorback/account/views.py
  adoorback/adoorback/utils/authentication.py
  adoorback/adoorback/utils/exceptions.py
Labels: bug

#676 (#651) add fallback logic for language
  adoorback/account/views.py
  adoorback/adoorback/settings/base.py
  adoorback/custom_fcm/views.py
  adoorback/notification/views.py
  adoorback/qna/views.py
Labels: bug

#679 (#677) add default me notes api
  adoorback/account/urls.py
  adoorback/account/views.py
Labels: bug

#680 (#651) fix language setting race condition
  adoorback/account/views.py
  adoorback/adoorback/middleware.py
  adoorback/adoorback/settings/base.py
  adoorback/adoorback/urls.py
  adoorback/notification/views.py
  adoorback/qna/views.py
Labels: bug

#681 (#651) add korean translation file
  adoorback/account/migrations/0029_alter_user_language.py
  adoorback/adoorback/locale/ko/LC_MESSAGES/django.mo
  adoorback/adoorback/locale/ko/LC_MESSAGES/django.po
Labels: bug
