Repository ssm0318/WhoamI-Today-backend, pull requests merged in 2025-01, with the labels that each got.

#425 (#424) default feed API
  adoorback/account/urls.py
  adoorback/account/views.py
Labels: feature

#428 (#426) like related APIs for default ver.
  adoorback/account/urls.py
  adoorback/account/views.py
  adoorback/note/serializers.py
  adoorback/note/urls.py
  adoorback/note/views.py
Labels: feature

#429 (#426) add friend note detail API for default ver.
  adoorback/note/urls.py
  adoorback/note/views.py
Labels: feature

#430 (#427) Ping API update
  adoorback/ping/models.py
  adoorback/ping/serializers.py
  adoorback/ping/urls.py
  adoorback/ping/views.py
Labels: feature

#434 (#431) fix ping GET API error
  adoorback/ping/views.py
Labels: bug

#441 (#440) ping mark as read by page
  adoorback/ping/views.py
Labels: feature

#443 (#442) exclude responses from default feed API
  adoorback/account/views.py
Labels: bug

#444 (#435) add friend_count to user/me/profile/
  adoorback/account/serializers.py
Labels: feature

#447 (#446) friend request/respond API for default ver.
  adoorback/account/serializers.py
  adoorback/account/urls.py
  adoorback/account/views.py
Labels: feature

#449 (#400, #448) remove friends field from user, change terminology
  adoorback/account/cron.py
  adoorback/account/migrations/0015_remove_user_friends_alter_connection_user1_choice_and_more.py
  adoorback/account/models.py
  adoorback/account/serializers.py
  adoorback/account/views.py
Labels: refactoring

#451 [#450] friend vs close friend implementation for ver.D and ver.E Common Features
  adoorback/note/migrations/0008_note_visibility.py
  adoorback/note/models.py
  adoorback/note/serializers.py
  adoorback/note/urls.py
  adoorback/note/views.py
  adoorback/qna/migrations/0008_response_visibility.py
  adoorback/qna/models.py
  adoorback/qna/serializers.py
  adoorback/qna/views.py
  adoorback/test/seed.py
Labels: feature
